spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306
    username: mysql
    password: mysql

server:
  port: 8080
  servlet:
    context-path: /ecsite

mybatis:
  mapper-locations:
    - classpath*:/com/ecsite/demo/mapper/*.xml

logging.level.org.springframework: DEBUG


